-- MySQL Script generated by MySQL Workbench
-- 12/21/16 21:33:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bootstrap_main
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bootstrap_main` ;

-- -----------------------------------------------------
-- Schema bootstrap_main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bootstrap_main` DEFAULT CHARACTER SET utf8 ;
USE `bootstrap_main` ;

-- -----------------------------------------------------
-- Table `bootstrap_main`.`new_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`new_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`institution` (
  `idinstitution` VARCHAR(10) NOT NULL,
  `inst_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstitution`),
  UNIQUE INDEX `idinstitution_UNIQUE` (`idinstitution` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `bio` TEXT NULL,
  `dob` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NULL,
  `dp_path` VARCHAR(45) NULL DEFAULT 'user/dp/default_pic',
  `institution_idinstitution` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  INDEX `fk_user_institution1_idx` (`institution_idinstitution` ASC),
  CONSTRAINT `fk_user_institution1`
    FOREIGN KEY (`institution_idinstitution`)
    REFERENCES `bootstrap_main`.`institution` (`idinstitution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`interests` (
  `idinterests` INT NOT NULL,
  `interest_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinterests`),
  UNIQUE INDEX `idinterests_UNIQUE` (`idinterests` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`catagory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`catagory` (
  `idcatagory` INT NOT NULL,
  `catagory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcatagory`),
  UNIQUE INDEX `idcatagory_UNIQUE` (`idcatagory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`projects` (
  `idprojects` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `xml_path` VARCHAR(255) NOT NULL,
  `catagory_idcatagory` INT NOT NULL,
  PRIMARY KEY (`idprojects`, `catagory_idcatagory`),
  UNIQUE INDEX `idprojects_UNIQUE` (`idprojects` ASC),
  UNIQUE INDEX `xml_path_UNIQUE` (`xml_path` ASC),
  INDEX `fk_projects_catagory1_idx` (`catagory_idcatagory` ASC),
  CONSTRAINT `fk_projects_catagory1`
    FOREIGN KEY (`catagory_idcatagory`)
    REFERENCES `bootstrap_main`.`catagory` (`idcatagory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`tags` (
  `idtags` INT NOT NULL,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtags`),
  UNIQUE INDEX `idtags_UNIQUE` (`idtags` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`follow` (
  `follows` INT NOT NULL,
  `follow` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`follows`, `follow`),
  INDEX `fk_user_has_user_user1_idx` (`follow` ASC),
  INDEX `fk_user_has_user_user_idx` (`follows` ASC),
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`follows`)
    REFERENCES `bootstrap_main`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`follow`)
    REFERENCES `bootstrap_main`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user_has_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user_has_interests` (
  `user_iduser` INT NOT NULL,
  `interests_idinterests` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `interests_idinterests`),
  INDEX `fk_user_has_interests_interests1_idx` (`interests_idinterests` ASC),
  INDEX `fk_user_has_interests_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_interests_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `bootstrap_main`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_interests_interests1`
    FOREIGN KEY (`interests_idinterests`)
    REFERENCES `bootstrap_main`.`interests` (`idinterests`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user_has_projects` (
  `projects_idprojects` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`projects_idprojects`, `user_iduser`),
  INDEX `fk_user_has_projects_projects1_idx` (`projects_idprojects` ASC),
  INDEX `fk_user_has_projects_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_projects_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `bootstrap_main`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_projects_projects1`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `bootstrap_main`.`projects` (`idprojects`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`projects_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`projects_has_tags` (
  `projects_idprojects` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`projects_idprojects`, `tags_idtags`),
  INDEX `fk_projects_has_tags_tags1_idx` (`tags_idtags` ASC),
  INDEX `fk_projects_has_tags_projects1_idx` (`projects_idprojects` ASC),
  CONSTRAINT `fk_projects_has_tags_projects1`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `bootstrap_main`.`projects` (`idprojects`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_projects_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `bootstrap_main`.`tags` (`idtags`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
