-- MySQL Script generated by MySQL Workbench
-- 12/29/16 20:49:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bootstrap_main
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bootstrap_main` ;

-- -----------------------------------------------------
-- Schema bootstrap_main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bootstrap_main` DEFAULT CHARACTER SET utf8 ;
USE `bootstrap_main` ;

-- -----------------------------------------------------
-- Table `bootstrap_main`.`new_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`new_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`institution` (
  `idinstitution` VARCHAR(10) NOT NULL,
  `inst_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstitution`),
  UNIQUE INDEX `idinstitution_UNIQUE` (`idinstitution` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `bio` TEXT NULL,
  `dob` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NULL,
  `dp_path` VARCHAR(45) NULL DEFAULT 'user/dp/default_pic',
  `institution_idinstitution` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`interests` (
  `idinterests` INT NOT NULL,
  `interest_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinterests`),
  UNIQUE INDEX `idinterests_UNIQUE` (`idinterests` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`catagory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`catagory` (
  `idcatagory` INT NOT NULL,
  `catagory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcatagory`),
  UNIQUE INDEX `idcatagory_UNIQUE` (`idcatagory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`projects` (
  `idprojects` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `xml_path` VARCHAR(255) NOT NULL,
  `catagory_idcatagory` INT NOT NULL,
  PRIMARY KEY (`idprojects`, `catagory_idcatagory`),
  UNIQUE INDEX `idprojects_UNIQUE` (`idprojects` ASC),
  UNIQUE INDEX `xml_path_UNIQUE` (`xml_path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`tags` (
  `idtags` INT NOT NULL,
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtags`),
  UNIQUE INDEX `idtags_UNIQUE` (`idtags` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`follow` (
  `follows` INT NOT NULL,
  `follow` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`follows`, `follow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user_has_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user_has_interests` (
  `user_iduser` INT NOT NULL,
  `interests_idinterests` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `interests_idinterests`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user_has_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user_has_projects` (
  `projects_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`projects_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`projects_has_tags` (
  `projects_idprojects` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`projects_idprojects`, `tags_idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`Notification` (
  `idNotification` INT NOT NULL,
  `sender` VARCHAR(45) NOT NULL,
  `receiver` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `ref_link` VARCHAR(255) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `read_status` TINYINT NOT NULL DEFAULT 0,
  `send_status` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idNotification`),
  UNIQUE INDEX `idNotification_UNIQUE` (`idNotification` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`contact` (
  `idcontact` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontact`),
  UNIQUE INDEX `idcontact_UNIQUE` (`idcontact` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`user_has_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`user_has_contact` (
  `user_iduser` INT NOT NULL,
  `contact_idcontact` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `contact_idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`pinned_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`pinned_projects` (
  `user_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `projects_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootstrap_main`.`pinned_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootstrap_main`.`pinned_projects` (
  `user_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `projects_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bootstrap_main`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `bootstrap_main`;
INSERT INTO `bootstrap_main`.`user` (`iduser`, `user_name`, `first_name`, `last_name`, `email`, `password`, `bio`, `dob`, `gender`, `dp_path`, `institution_idinstitution`) VALUES (1, 'fz09', 'araf', 'adnan', 'aiadnan1993', '123', NULL, '09-02-1993', 'male', NULL, '1');

COMMIT;

